hubert:
  feat_emb_dim: 40
  pos_emb_type: conv
  pos_conv_depth: 1
  conv_pos: 128
  conv_pos_groups: 16
  encoder_layers: 12
  encoder_embed_dim: 768
  encoder_ffn_embed_dim: 3072
  encoder_attention_heads: 12
  activation_fn: gelu
  layer_norm_first: false
  attention_type: original
  num_cluster: 512
  pred_masked_weight: 1.0
  pred_nomask_weight: 0.0
  skip_masked: false
  skip_nomask: true
  mask_prob: 0.7
  mask_length: 10
  mask_selection: static
  mask_other: 0.0
  no_mask_overlap: false
  mask_min_space: 1
  learnable_mask_emb: false
  mask_before_proj: true
  dropout: 0.1
  attention_dropout: 0.1
  activation_dropout: 0.1
  encoder_layerdrop: 0.0
task:
  sequence_length: 1500
adjust_init_weight:
  num_cluster: 512