runner:
  n_epochs: 150
  total_steps: 474450
  gradient_clipping: 10.0
  gradient_accumulate_steps: 1
  log_step: 1000
  save_step: 1000
  max_keep: 5
  fp16: false

optimizer:
  lr: 0.0001
  betas: [0.9, 0.999]
  eps: 1.0e-08
  weight_decay: 0

datarc:
  fbank_scp: data/sample10/sample10.fbank.scp
  fbank_mean_var: data/sample10/sample10.fbank.mean-var
  bas_scp: data/sample10/sample10.bas.scp
